package hibernate;
// Generated Mar 15, 2016 9:21:48 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER"
    ,schema="NBUSER"
)
public class Customer  implements java.io.Serializable {


     private int id;
     private String firstname;
     private String lastname;
     private String city;

    public Customer() {
    }

	
    public Customer(int id) {
        this.id = id;
    }
    public Customer(int id, String firstname, String lastname, String city) {
       this.id = id;
       this.firstname = firstname;
       this.lastname = lastname;
       this.city = city;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="FIRSTNAME", length=10)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="LASTNAME", length=10)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="CITY", length=10)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    @Override
    public String toString() {
        return "Customer{" + "id=" + id + ", firstname=" + firstname + ", lastname=" + lastname + ", city=" + city + '}';
    }




}


